### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by caoimhemalone** [StephenWeiXu/react-scrollspy-nav#14]
I'm getting multiple console errors saying 'Uncaught TypeError: Cannot read property 'offsetTop' of null'. Is there a fix for this?

**Comment by StephenWeiXu** [comment]
@caoimhemalone That error happens when an element that it's trying to apply `offsetTop` to does not exist in the DOM. See its usage [here](https://github.com/StephenWeiXu/react-scrollspy-nav/blob/master/src/lib/ScrollspyNav.js#L28).

Can you double check the `scrollTargetIds` is passed correctly to `ScrollspyNav`, and each string in the `scrollTargetIds` list is used as `id` on an element that exists in the DOM?

As a reference, see a quick usage example [here](https://github.com/StephenWeiXu/react-scrollspy-nav/blob/master/src/App.js#L43)
